package com.myspace.medicalclaimstest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class coverageHolder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Coverage Holder Email Address")
	private java.lang.String chEmail;
	@org.kie.api.definition.type.Label("Coverage Holder First Name")
	private java.lang.String chFirstName;
	@org.kie.api.definition.type.Label("Coverage Holder Last Name")
	private java.lang.String chLastName;
	@org.kie.api.definition.type.Label("Coverage Holder Medical Authorization")
	private java.lang.Boolean chMedAuth;
	@org.kie.api.definition.type.Label("Coverage Holder SSN")
	private java.lang.String chSSN;
	@org.kie.api.definition.type.Label("Coverage Holder Initial Coverage Date")
	private java.util.Date chInitCovDt;

	@org.kie.api.definition.type.Label("Coverage Holder Coverages")
	private java.util.List<com.myspace.medicalclaimstest.chCoverages> chCoverages;

	@org.kie.api.definition.type.Label(value = "Existing Claims")
	private java.util.List<com.myspace.medicalclaimstest.existingClaims> existingClaims;

	public coverageHolder() {
	}

	public java.lang.String getChEmail() {
		return this.chEmail;
	}

	public void setChEmail(java.lang.String chEmail) {
		this.chEmail = chEmail;
	}

	public java.lang.String getChFirstName() {
		return this.chFirstName;
	}

	public void setChFirstName(java.lang.String chFirstName) {
		this.chFirstName = chFirstName;
	}

	public java.lang.String getChLastName() {
		return this.chLastName;
	}

	public void setChLastName(java.lang.String chLastName) {
		this.chLastName = chLastName;
	}

	public java.lang.Boolean getChMedAuth() {
		return this.chMedAuth;
	}

	public void setChMedAuth(java.lang.Boolean chMedAuth) {
		this.chMedAuth = chMedAuth;
	}

	public java.lang.String getChSSN() {
		return this.chSSN;
	}

	public void setChSSN(java.lang.String chSSN) {
		this.chSSN = chSSN;
	}

	public java.util.Date getChInitCovDt() {
		return this.chInitCovDt;
	}

	public void setChInitCovDt(java.util.Date chInitCovDt) {
		this.chInitCovDt = chInitCovDt;
	}

	public java.util.List<com.myspace.medicalclaimstest.chCoverages> getChCoverages() {
		return this.chCoverages;
	}

	public void setChCoverages(
			java.util.List<com.myspace.medicalclaimstest.chCoverages> chCoverages) {
		this.chCoverages = chCoverages;
	}

	@Override
	public String toString() {
		return "coverageHolder [chEmail=" + chEmail + ", chFirstName="
				+ chFirstName + ", chLastName=" + chLastName + ", chMedAuth="
				+ chMedAuth + ", chSSN=" + chSSN + ", chInitCovDt="
				+ chInitCovDt + ", chCoverages=" + chCoverages + ", existingClaims=" + existingClaims + "]";
	}

	public java.util.List<com.myspace.medicalclaimstest.existingClaims> getExistingClaims() {
		return this.existingClaims;
	}

	public void setExistingClaims(
			java.util.List<com.myspace.medicalclaimstest.existingClaims> existingClaims) {
		this.existingClaims = existingClaims;
	}

	public coverageHolder(
			java.lang.String chEmail,
			java.lang.String chFirstName,
			java.lang.String chLastName,
			java.lang.Boolean chMedAuth,
			java.lang.String chSSN,
			java.util.Date chInitCovDt,
			java.util.List<com.myspace.medicalclaimstest.chCoverages> chCoverages,
			java.util.List<com.myspace.medicalclaimstest.existingClaims> existingClaims) {
		this.chEmail = chEmail;
		this.chFirstName = chFirstName;
		this.chLastName = chLastName;
		this.chMedAuth = chMedAuth;
		this.chSSN = chSSN;
		this.chInitCovDt = chInitCovDt;
		this.chCoverages = chCoverages;
		this.existingClaims = existingClaims;
	}

}