package com.myspace.medicalclaimstest;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Employer Group")
public class employerGroup implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Group Number")
	private java.lang.String groupNumber;
	@org.kie.api.definition.type.Label("Group Name")
	private java.lang.String groupName;
	@org.kie.api.definition.type.Label("Group Status")
	@org.kie.api.definition.type.Description("The current status of our relationship with the group (Active, Inactive, etc.)")
	private java.lang.String groupStatus;

	@org.kie.api.definition.type.Label(value = "Group Coverages")
	private java.util.List<com.myspace.medicalclaimstest.groupCoverages> groupCoverage;

	public employerGroup() {
	}

	public java.lang.String getGroupNumber() {
		return this.groupNumber;
	}

	public void setGroupNumber(java.lang.String groupNumber) {
		this.groupNumber = groupNumber;
	}

	public java.lang.String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(java.lang.String groupName) {
		this.groupName = groupName;
	}

	public java.lang.String getGroupStatus() {
		return this.groupStatus;
	}

	public void setGroupStatus(java.lang.String groupStatus) {
		this.groupStatus = groupStatus;
	}

	@Override
	public String toString() {
		return "employerGroup [groupNumber=" + groupNumber + ", groupName="
				+ groupName + ", groupStatus=" + groupStatus +  ", groupCoverage=" + groupCoverage + "]";
	}

	public java.util.List<com.myspace.medicalclaimstest.groupCoverages> getGroupCoverage() {
		return this.groupCoverage;
	}

	public void setGroupCoverage(
			java.util.List<com.myspace.medicalclaimstest.groupCoverages> groupCoverage) {
		this.groupCoverage = groupCoverage;
	}

	public employerGroup(
			java.lang.String groupNumber,
			java.lang.String groupName,
			java.lang.String groupStatus,
			java.util.List<com.myspace.medicalclaimstest.groupCoverages> groupCoverage) {
		this.groupNumber = groupNumber;
		this.groupName = groupName;
		this.groupStatus = groupStatus;
		this.groupCoverage = groupCoverage;
	}

}