package com.myspace.medicalclaimstest;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("medicalEvent")
@org.kie.api.definition.type.Description("Incoming medical event data")
public class medicalEvent implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("eventID")
	private java.lang.Double eventID;
	@org.kie.api.definition.type.Label("custSSN")
	private java.lang.Integer custSSN;
	@org.kie.api.definition.type.Label("custFirstName")
	private java.lang.String custFirstName;
	@org.kie.api.definition.type.Label("custLastName")
	private java.lang.String custLastName;
	@org.kie.api.definition.type.Label("revCode")
	private java.lang.String revCode;
	@org.kie.api.definition.type.Label("icd10Code")
	private java.lang.String icd10Code;
	@org.kie.api.definition.type.Label("procCode")
	private java.lang.String procCode;
	@org.kie.api.definition.type.Label("custDOB")
	private java.util.Date custDOB;
	@org.kie.api.definition.type.Label("custGender")
	private java.lang.String custGender;
	@org.kie.api.definition.type.Label("serviceStartDt")
	private java.util.Date serviceStartDt;
	@org.kie.api.definition.type.Label("serviceEndDt")
	private java.util.Date serviceEndDt;
	@org.kie.api.definition.type.Label("providerName")
	private java.lang.String providerName;
	@org.kie.api.definition.type.Label("custRelationship")
	private java.lang.String custRelationship;

	@org.kie.api.definition.type.Label("Probability Results")
	private java.util.List<com.myspace.medicalclaimstest.medicalTriggerResults> probResults;

	@org.kie.api.definition.type.Label(value = "Customer is Active")
	private java.lang.Boolean custActive;

	@org.kie.api.definition.type.Label(value = "Group Is Active")
	private java.lang.Boolean groupActive;

	@org.kie.api.definition.type.Label(value = "Customer Has Email Address")
	private boolean custEmail;

	public medicalEvent() {
	}

	public java.lang.Double getEventID() {
		return this.eventID;
	}

	public void setEventID(java.lang.Double eventID) {
		this.eventID = eventID;
	}

	public java.lang.Integer getCustSSN() {
		return this.custSSN;
	}

	public void setCustSSN(java.lang.Integer custSSN) {
		this.custSSN = custSSN;
	}

	public java.lang.String getCustFirstName() {
		return this.custFirstName;
	}

	public void setCustFirstName(java.lang.String custFirstName) {
		this.custFirstName = custFirstName;
	}

	public java.lang.String getCustLastName() {
		return this.custLastName;
	}

	public void setCustLastName(java.lang.String custLastName) {
		this.custLastName = custLastName;
	}

	public java.lang.String getRevCode() {
		return this.revCode;
	}

	public void setRevCode(java.lang.String revCode) {
		this.revCode = revCode;
	}

	public java.lang.String getIcd10Code() {
		return this.icd10Code;
	}

	public void setIcd10Code(java.lang.String icd10Code) {
		this.icd10Code = icd10Code;
	}

	public java.lang.String getProcCode() {
		return this.procCode;
	}

	public void setProcCode(java.lang.String procCode) {
		this.procCode = procCode;
	}

	public java.util.Date getCustDOB() {
		return this.custDOB;
	}

	public void setCustDOB(java.util.Date custDOB) {
		this.custDOB = custDOB;
	}

	public java.lang.String getCustGender() {
		return this.custGender;
	}

	public void setCustGender(java.lang.String custGender) {
		this.custGender = custGender;
	}

	public java.util.Date getServiceStartDt() {
		return this.serviceStartDt;
	}

	public void setServiceStartDt(java.util.Date serviceStartDt) {
		this.serviceStartDt = serviceStartDt;
	}

	public java.util.Date getServiceEndDt() {
		return this.serviceEndDt;
	}

	public void setServiceEndDt(java.util.Date serviceEndDt) {
		this.serviceEndDt = serviceEndDt;
	}

	public java.lang.String getProviderName() {
		return this.providerName;
	}

	public void setProviderName(java.lang.String providerName) {
		this.providerName = providerName;
	}

	public java.lang.String getCustRelationship() {
		return this.custRelationship;
	}

	public void setCustRelationship(java.lang.String custRelationship) {
		this.custRelationship = custRelationship;
	}

	public java.util.List<com.myspace.medicalclaimstest.medicalTriggerResults> getProbResults() {
		return this.probResults;
	}

	public void setProbResults(
			java.util.List<com.myspace.medicalclaimstest.medicalTriggerResults> probResults) {
		this.probResults = probResults;
	}

	public java.lang.Boolean getCustActive() {
		return this.custActive;
	}

	public void setCustActive(java.lang.Boolean custActive) {
		this.custActive = custActive;
	}

	public java.lang.Boolean getGroupActive() {
		return this.groupActive;
	}

	public void setGroupActive(java.lang.Boolean groupActive) {
		this.groupActive = groupActive;
	}

	public boolean isCustEmail() {
		return this.custEmail;
	}

	public void setCustEmail(boolean custEmail) {
		this.custEmail = custEmail;
	}

	public medicalEvent(
			java.lang.Double eventID,
			java.lang.Integer custSSN,
			java.lang.String custFirstName,
			java.lang.String custLastName,
			java.lang.String revCode,
			java.lang.String icd10Code,
			java.lang.String procCode,
			java.util.Date custDOB,
			java.lang.String custGender,
			java.util.Date serviceStartDt,
			java.util.Date serviceEndDt,
			java.lang.String providerName,
			java.lang.String custRelationship,
			java.util.List<com.myspace.medicalclaimstest.medicalTriggerResults> probResults,
			java.lang.Boolean custActive, java.lang.Boolean groupActive,
			boolean custEmail) {
		this.eventID = eventID;
		this.custSSN = custSSN;
		this.custFirstName = custFirstName;
		this.custLastName = custLastName;
		this.revCode = revCode;
		this.icd10Code = icd10Code;
		this.procCode = procCode;
		this.custDOB = custDOB;
		this.custGender = custGender;
		this.serviceStartDt = serviceStartDt;
		this.serviceEndDt = serviceEndDt;
		this.providerName = providerName;
		this.custRelationship = custRelationship;
		this.probResults = probResults;
		this.custActive = custActive;
		this.groupActive = groupActive;
		this.custEmail = custEmail;
	}
	
	@Override
	public String toString() {
		return "medicalEvent [eventID=" + eventID + ", custSSN=" + custSSN + ", custFirstName=" + custFirstName
				+ ", custLastName=" + custLastName + ", custActive="
				+ custActive + ", groupActive=" + groupActive + ", custEmail=" + custEmail 
				+ ", revCode=" + revCode + ", icd10Code=" + icd10Code + ", procCode="
				+ procCode + ", custDOB=" + custDOB + ", custGender=" + custGender + ", serviceStartDt="
				+ serviceStartDt + ", serviceEndDt=" + serviceEndDt + ", providerName=" + providerName
				+ ", custRelationship=" + custRelationship + ", probResults=" + probResults + "]";
	}

}