package com.myspace.medicalclaimstest;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Group Coverages")
@org.kie.api.definition.type.Description("The coverages that a group offers.")
public class groupCoverages implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Groups Product")
	private java.lang.String groupProduct;
	@org.kie.api.definition.type.Label(value = "Product Status")
	private java.lang.String prodStatus;

	public groupCoverages() {
	}

	public java.lang.String getGroupProduct() {
		return this.groupProduct;
	}

	public void setGroupProduct(java.lang.String groupProduct) {
		this.groupProduct = groupProduct;
	}

	public java.lang.String getProdStatus() {
		return this.prodStatus;
	}

	public void setProdStatus(java.lang.String prodStatus) {
		this.prodStatus = prodStatus;
	}

	public groupCoverages(java.lang.String groupProduct,
			java.lang.String prodStatus) {
		this.groupProduct = groupProduct;
		this.prodStatus = prodStatus;
	}

}