package com.myspace.claimsprocessing;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Claim")
public class Claim implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Claim Identifier")
	private java.lang.String claimID;

	@org.kie.api.definition.type.Label("Claim Amount")
	private java.lang.Integer claimAmount;

	@org.kie.api.definition.type.Label("Product Code")
	private java.lang.String product;

	@org.kie.api.definition.type.Label("SSN")
	private java.lang.String subscriberSSN;

	@org.kie.api.definition.type.Label("Date of the procedure")
	private java.util.Date procedureDate;

	@org.kie.api.definition.type.Label(value = "Validity Flag")
	private java.lang.Boolean validFlag;

	@org.kie.api.definition.type.Label(value = "Validity Reason")
	private java.lang.String validityReason;

	public Claim() {
	}

	public java.lang.String getClaimID() {
		return this.claimID;
	}

	public void setClaimID(java.lang.String claimID) {
		this.claimID = claimID;
	}

	public java.lang.Integer getClaimAmount() {
		return this.claimAmount;
	}

	public void setClaimAmount(java.lang.Integer claimAmount) {
		this.claimAmount = claimAmount;
	}

	public java.lang.String getProduct() {
		return this.product;
	}

	public void setProduct(java.lang.String product) {
		this.product = product;
	}

	public java.lang.String getSubscriberSSN() {
		return this.subscriberSSN;
	}

	public void setSubscriberSSN(java.lang.String subscriberSSN) {
		this.subscriberSSN = subscriberSSN;
	}

	public java.util.Date getProcedureDate() {
		return this.procedureDate;
	}

	public void setProcedureDate(java.util.Date procedureDate) {
		this.procedureDate = procedureDate;
	}

	public java.lang.Boolean getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(java.lang.Boolean validFlag) {
		this.validFlag = validFlag;
	}

	public java.lang.String getValidityReason() {
		return this.validityReason;
	}

	public void setValidityReason(java.lang.String validityReason) {
		this.validityReason = validityReason;
	}

	public Claim(java.lang.String claimID, java.lang.Integer claimAmount,
			java.lang.String product, java.lang.String subscriberSSN,
			java.util.Date procedureDate, java.lang.Boolean validFlag,
			java.lang.String validityReason) {
		this.claimID = claimID;
		this.claimAmount = claimAmount;
		this.product = product;
		this.subscriberSSN = subscriberSSN;
		this.procedureDate = procedureDate;
		this.validFlag = validFlag;
		this.validityReason = validityReason;
	}

}