package com.myspace.claimsprocessing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MedicalCodeInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Code number")
	private java.lang.String medicalCode;
	@org.kie.api.definition.type.Label(value = "code validity")
	private java.lang.Boolean validCode;

	public MedicalCodeInfo() {
	}

	public java.lang.String getMedicalCode() {
		return this.medicalCode;
	}

	public void setMedicalCode(java.lang.String medicalCode) {
		this.medicalCode = medicalCode;
	}

	public java.lang.Boolean getValidCode() {
		return this.validCode;
	}

	public void setValidCode(java.lang.Boolean validCode) {
		this.validCode = validCode;
	}

	public MedicalCodeInfo(java.lang.String medicalCode,
			java.lang.Boolean validCode) {
		this.medicalCode = medicalCode;
		this.validCode = validCode;
	}

}