package com.myspace.rits;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Board implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Board Part #")
	private java.lang.String boardPartNum;
	@org.kie.api.definition.type.Label("Serial Number")
	private Short serialNum;
	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("Manufacturer")
	private java.lang.String manufacturer;
	@org.kie.api.definition.type.Label("Test Procedure")
	private java.lang.String testProcedure;
	@org.kie.api.definition.type.Label("Repair Value")
	private java.lang.Double price;

	@org.kie.api.definition.type.Label("Components Used")
	private java.util.List<com.myspace.rits.Components> components;

	public Board() {
	}

	public java.lang.String getBoardPartNum() {
		return this.boardPartNum;
	}

	public void setBoardPartNum(java.lang.String boardPartNum) {
		this.boardPartNum = boardPartNum;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(java.lang.String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public java.lang.String getTestProcedure() {
		return this.testProcedure;
	}

	public void setTestProcedure(java.lang.String testProcedure) {
		this.testProcedure = testProcedure;
	}

	public java.lang.Double getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Double price) {
		this.price = price;
	}

	public java.util.List<com.myspace.rits.Components> getComponents() {
		return this.components;
	}

	public void setComponents(
			java.util.List<com.myspace.rits.Components> components) {
		this.components = components;
	}

	public java.lang.Short getSerialNum() {
		return this.serialNum;
	}

	public void setSerialNum(java.lang.Short serialNum) {
		this.serialNum = serialNum;
	}

	public Board(java.lang.String boardPartNum, java.lang.Short serialNum,
			java.lang.String description, java.lang.String manufacturer,
			java.lang.String testProcedure, java.lang.Double price,
			java.util.List<com.myspace.rits.Components> components) {
		this.boardPartNum = boardPartNum;
		this.serialNum = serialNum;
		this.description = description;
		this.manufacturer = manufacturer;
		this.testProcedure = testProcedure;
		this.price = price;
		this.components = components;
	}

}