package com.myspace.rits;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CrossCharge implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Charge Amount($)")
	private java.lang.Double chargeAmount;
	@org.kie.api.definition.type.Label(value = "Customer Name")
	private java.lang.String customerName;
	@org.kie.api.definition.type.Label(value = "ChargeDate")
	private java.util.Date chargeDate;

	public CrossCharge() {
	}

	public java.lang.Double getChargeAmount() {
		return this.chargeAmount;
	}

	public void setChargeAmount(java.lang.Double chargeAmount) {
		this.chargeAmount = chargeAmount;
	}

	public java.lang.String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(java.lang.String customerName) {
		this.customerName = customerName;
	}

	public java.util.Date getChargeDate() {
		return this.chargeDate;
	}

	public void setChargeDate(java.util.Date chargeDate) {
		this.chargeDate = chargeDate;
	}

	public CrossCharge(java.lang.Double chargeAmount,
			java.lang.String customerName, java.util.Date chargeDate) {
		this.chargeAmount = chargeAmount;
		this.customerName = customerName;
		this.chargeDate = chargeDate;
	}

}