package com.myspace.rits;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Shipment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Shipment Date")
	private java.util.Date shipmentDate;
	@org.kie.api.definition.type.Label(value = "Shipment Method")
	private java.lang.String method;
	@org.kie.api.definition.type.Label(value = "Priority")
	private java.lang.String priority;
	@org.kie.api.definition.type.Label(value = "Tracking Number")
	private java.lang.String trackingNumber;
	@org.kie.api.definition.type.Label(value = "Cost")
	private java.lang.Double shipmentCost;

	public Shipment() {
	}

	public java.util.Date getShipmentDate() {
		return this.shipmentDate;
	}

	public void setShipmentDate(java.util.Date shipmentDate) {
		this.shipmentDate = shipmentDate;
	}

	public java.lang.String getMethod() {
		return this.method;
	}

	public void setMethod(java.lang.String method) {
		this.method = method;
	}

	public java.lang.String getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.String priority) {
		this.priority = priority;
	}

	public java.lang.String getTrackingNumber() {
		return this.trackingNumber;
	}

	public void setTrackingNumber(java.lang.String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	public java.lang.Double getShipmentCost() {
		return this.shipmentCost;
	}

	public void setShipmentCost(java.lang.Double shipmentCost) {
		this.shipmentCost = shipmentCost;
	}

	public Shipment(java.util.Date shipmentDate, java.lang.String method,
			java.lang.String priority, java.lang.String trackingNumber,
			java.lang.Double shipmentCost) {
		this.shipmentDate = shipmentDate;
		this.method = method;
		this.priority = priority;
		this.trackingNumber = trackingNumber;
		this.shipmentCost = shipmentCost;
	}

}