package com.myspace.rits;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WorkOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Work order creation Date")
	private java.util.Date createDate;
	@org.kie.api.definition.type.Label("Work order completion date")
	private java.util.Date completionDate;
	@org.kie.api.definition.type.Label("Status of Work Order")
	private java.lang.String status;
	@org.kie.api.definition.type.Label("Technician name")
	private java.lang.String technician;
	@org.kie.api.definition.type.Label("Condition")
	private java.lang.String condition;

	public WorkOrder() {
	}

	public java.util.Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(java.util.Date createDate) {
		this.createDate = createDate;
	}

	public java.util.Date getCompletionDate() {
		return this.completionDate;
	}

	public void setCompletionDate(java.util.Date completionDate) {
		this.completionDate = completionDate;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getTechnician() {
		return this.technician;
	}

	public void setTechnician(java.lang.String technician) {
		this.technician = technician;
	}

	public java.lang.String getCondition() {
		return this.condition;
	}

	public void setCondition(java.lang.String condition) {
		this.condition = condition;
	}

	public WorkOrder(java.util.Date createDate, java.util.Date completionDate,
			java.lang.String status, java.lang.String technician,
			java.lang.String condition) {
		this.createDate = createDate;
		this.completionDate = completionDate;
		this.status = status;
		this.technician = technician;
		this.condition = condition;
	}

}