package com.myspace;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class medicalEventCodeEval implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.String> icd10Matches;
	private java.util.List<java.lang.String> icd10Probabilities;
	private java.util.List<java.lang.String> icd10BenefitTriggers;
	private java.util.List<java.lang.String> icd10Products;

	public medicalEventCodeEval() {
	}

	public java.util.List<java.lang.String> getIcd10Matches() {
		return this.icd10Matches;
	}

	public void setIcd10Matches(java.util.List<java.lang.String> icd10Matches) {
		this.icd10Matches = icd10Matches;
	}

	public java.util.List<java.lang.String> getIcd10Probabilities() {
		return this.icd10Probabilities;
	}

	public void setIcd10Probabilities(
			java.util.List<java.lang.String> icd10Probabilities) {
		this.icd10Probabilities = icd10Probabilities;
	}

	public java.util.List<java.lang.String> getIcd10BenefitTriggers() {
		return this.icd10BenefitTriggers;
	}

	public void setIcd10BenefitTriggers(
			java.util.List<java.lang.String> icd10BenefitTriggers) {
		this.icd10BenefitTriggers = icd10BenefitTriggers;
	}

	public java.util.List<java.lang.String> getIcd10Products() {
		return this.icd10Products;
	}

	public void setIcd10Products(java.util.List<java.lang.String> icd10Products) {
		this.icd10Products = icd10Products;
	}

	public medicalEventCodeEval(java.util.List<java.lang.String> icd10Matches,
			java.util.List<java.lang.String> icd10Probabilities,
			java.util.List<java.lang.String> icd10BenefitTriggers,
			java.util.List<java.lang.String> icd10Products) {
		this.icd10Matches = icd10Matches;
		this.icd10Probabilities = icd10Probabilities;
		this.icd10BenefitTriggers = icd10BenefitTriggers;
		this.icd10Products = icd10Products;
	}

}